Python 2.7:
  script:
  - py_version=2.7
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - export EXTRA_INSTALL="numpy"
  - export REQUIREMENTS_TXT=requirements.dev.txt
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - linux
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3:
  script:
  - py_version=3
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - export EXTRA_INSTALL="numpy"
  - export REQUIREMENTS_TXT=requirements.dev.txt
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  - linux
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh pudb test"
  tags:
  - python3
  except:
  - tags

Documentation:
  script:
  - EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3
  only:
  - master
