language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
    - pip install -r requirements.dev.txt
    - "pip install -e ."

# command to run tests
script:
    - "(cd test && pytest --cov=pudb)"

after_success:
  - bash upload_coverage.sh

sudo: false
